services:
  valkey-node-0:
    image: bitnami/valkey-cluster:7.2.5-debian-12-r4
    networks:
      cluster_subnet:
        ipv4_address: 172.16.1.2
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
      - 'VALKEY_NODES=valkey-node-0 valkey-node-1 valkey-node-2 valkey-node-3 valkey-node-4 valkey-node-5'
    healthcheck: &healthcheck
      test: [ "CMD-SHELL", "OUT=`valkey-cli cluster slots`; echo $$OUT | grep 172.16.1.2 || exit 1; echo $$OUT | grep 172.16.1.3 || exit 1; echo $$OUT | grep 172.16.1.4 || exit 1; echo $$OUT | grep 172.16.1.5 || exit 1; echo $$OUT | grep 172.16.1.6 || exit 1; echo $$OUT | grep 172.16.1.7 || exit 1;" ]
      interval: 1s
      timeout: 3s
      retries: 30

  valkey-node-1:
    image: bitnami/valkey-cluster:7.2.5-debian-12-r4
    networks:
      cluster_subnet:
        ipv4_address: 172.16.1.3
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
      - 'VALKEY_NODES=valkey-node-0 valkey-node-1 valkey-node-2 valkey-node-3 valkey-node-4 valkey-node-5'
    healthcheck: *healthcheck

  valkey-node-2:
    image: bitnami/valkey-cluster:7.2.5-debian-12-r4
    networks:
      cluster_subnet:
        ipv4_address: 172.16.1.4
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
      - 'VALKEY_NODES=valkey-node-0 valkey-node-1 valkey-node-2 valkey-node-3 valkey-node-4 valkey-node-5'
    healthcheck: *healthcheck

  valkey-node-3:
    image: bitnami/valkey-cluster:7.2.5-debian-12-r4
    networks:
      cluster_subnet:
        ipv4_address: 172.16.1.5
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
      - 'VALKEY_NODES=valkey-node-0 valkey-node-1 valkey-node-2 valkey-node-3 valkey-node-4 valkey-node-5'
    healthcheck: *healthcheck

  valkey-node-4:
    image: bitnami/valkey-cluster:7.2.5-debian-12-r4
    networks:
      cluster_subnet:
        ipv4_address: 172.16.1.6
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
      - 'VALKEY_NODES=valkey-node-0 valkey-node-1 valkey-node-2 valkey-node-3 valkey-node-4 valkey-node-5'
    healthcheck: *healthcheck

  valkey-node-5:
    image: bitnami/valkey-cluster:7.2.5-debian-12-r4
    networks:
      cluster_subnet:
        ipv4_address: 172.16.1.7
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
      - 'VALKEY_NODES=valkey-node-0 valkey-node-1 valkey-node-2 valkey-node-3 valkey-node-4 valkey-node-5'
    healthcheck: *healthcheck

  valkey-cluster-init:
    image: bitnami/valkey-cluster:7.2.5-debian-12-r4
    networks:
      cluster_subnet:
        ipv4_address: 172.16.1.8
    depends_on:
      - valkey-node-0
      - valkey-node-1
      - valkey-node-2
      - valkey-node-3
      - valkey-node-4
      - valkey-node-5
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
      - 'VALKEY_CLUSTER_REPLICAS=1'
      - 'VALKEY_NODES=valkey-node-0 valkey-node-1 valkey-node-2 valkey-node-3 valkey-node-4 valkey-node-5'
      - 'VALKEY_CLUSTER_CREATOR=yes'

  shotover-0:
    networks:
      cluster_subnet:
        ipv4_address: 172.16.1.9
    depends_on:
      valkey-node-0:
        condition: service_healthy
      valkey-node-1:
        condition: service_healthy
      valkey-node-2:
        condition: service_healthy
      valkey-node-3:
        condition: service_healthy
      valkey-node-4:
        condition: service_healthy
      valkey-node-5:
        condition: service_healthy
    image: shotover/shotover-proxy:v0.6.0
    volumes:
      - .:/config

networks:
  cluster_subnet:
    name: cluster_subnet
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.1.0/24
          gateway: 172.16.1.1
