services:
  redis-node-0:
    image: bitnami/redis-cluster:6.0-debian-10
    networks:
      cluster_subnet:
        ipv4_address: 172.16.1.2
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'
    healthcheck: &healthcheck
      test:
        [
          "CMD-SHELL",
          "OUT=`redis-cli cluster slots`;
          echo $$OUT | grep 172.16.1.2 || exit 1;
          echo $$OUT | grep 172.16.1.3 || exit 1;
          echo $$OUT | grep 172.16.1.4 || exit 1;
          echo $$OUT | grep 172.16.1.5 || exit 1;
          echo $$OUT | grep 172.16.1.6 || exit 1;
          echo $$OUT | grep 172.16.1.7 || exit 1;"
        ]
      interval: 1s
      timeout: 3s
      retries: 30

  redis-node-1:
    image: bitnami/redis-cluster:6.0-debian-10
    networks:
      cluster_subnet:
        ipv4_address: 172.16.1.3
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'
    healthcheck: *healthcheck

  redis-node-2:
    image: bitnami/redis-cluster:6.0-debian-10
    networks:
      cluster_subnet:
        ipv4_address: 172.16.1.4
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'
    healthcheck: *healthcheck

  redis-node-3:
    image: bitnami/redis-cluster:6.0-debian-10
    networks:
      cluster_subnet:
        ipv4_address: 172.16.1.5
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'
    healthcheck: *healthcheck

  redis-node-4:
    image: bitnami/redis-cluster:6.0-debian-10
    networks:
      cluster_subnet:
        ipv4_address: 172.16.1.6
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'
    healthcheck: *healthcheck

  redis-node-5:
    image: bitnami/redis-cluster:6.0-debian-10
    networks:
      cluster_subnet:
        ipv4_address: 172.16.1.7
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'
    healthcheck: *healthcheck

  redis-cluster-init:
    image: bitnami/redis-cluster:6.0-debian-10
    networks:
      cluster_subnet:
        ipv4_address: 172.16.1.8
    depends_on:
      - redis-node-0
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
      - redis-node-5
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
      - 'REDIS_CLUSTER_REPLICAS=1'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'
      - 'REDIS_CLUSTER_CREATOR=yes'

  shotover-0:
    networks:
      cluster_subnet:
        ipv4_address: 172.16.1.9
    depends_on:
      redis-node-0:
        condition: service_healthy
      redis-node-1:
        condition: service_healthy
      redis-node-2:
        condition: service_healthy
      redis-node-3:
        condition: service_healthy
      redis-node-4:
        condition: service_healthy
      redis-node-5:
        condition: service_healthy
    image: shotover/shotover-proxy:v0.5.3
    volumes:
      - .:/config

networks:
  cluster_subnet:
    name: cluster_subnet
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.1.0/24
          gateway: 172.16.1.1
