networks:
  cassandra_subnet:
    name: cassandra_subnet
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.1.0/24
          gateway: 172.16.1.1

services:
  cassandra-one:
    image: bitnami/cassandra:4.0.6
    networks:
      cassandra_subnet:
        ipv4_address: 172.16.1.2
    environment: &environment
      CASSANDRA_SEEDS: "cassandra-one,cassandra-two,cassandra-three"
      MAX_HEAP_SIZE: "400M"
      MIN_HEAP_SIZE: "400M"
      HEAP_NEWSIZE: "48M"
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
      CASSANDRA_CLUSTER_NAME: TestCluster
      CASSANDRA_DC: dc1
      CASSANDRA_RACK: rack1
    expose:
      - 9042

  cassandra-two:
    image: bitnami/cassandra:4.0.6
    networks:
      cassandra_subnet:
        ipv4_address: 172.16.1.3
    environment: *environment
    expose:
      - 9042

  cassandra-three:
    image: bitnami/cassandra:4.0.6
    networks:
      cassandra_subnet:
        ipv4_address: 172.16.1.4
    environment: *environment
    expose:
      - 9042

  shotover-one:
    restart: always
    depends_on:
      - cassandra-one
      - cassandra-two
      - cassandra-three
    image: shotover/shotover-proxy:v0.4.1
    networks:
      cassandra_subnet:
        ipv4_address: 172.16.1.5
    volumes:
      - .:/config
    expose:
      - 9042
